SET GLOBAL master_info_repository = 'TABLE';
SET GLOBAL relay_log_info_repository = 'TABLE';
CHANGE MASTER TO
MASTER_HOST='BENDERRODIGUEZ',
MASTER_USER='repl',
MASTER_PASSWORD='slavepass',
MASTER_AUTO_POSITION=1
FOR CHANNEL 'BENDERRODIGUEZ';
START SLAVE;
SHOW SLAVE STATUS \G;
